# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Suryadana
email: suryadana80@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am an simple person which want to learn more and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: suryadana
github_username:  suryadana

# Build settings
markdown: kramdown
theme: jekyll-theme-hydeout
plugins:
  - jekyll-feed
  - jekyll-paginate


# Sass
sass:
  sass_dir: _sass
  style: compressed

image_profile: "/assets/images/profile.jpg"
paginate:         5
sidebar_home_link:  true

disqus:
  shortname: suryadana

# Timeline
color: "#ffffff"
collections:
  posts:
    title: Posts
    output: true
  steps:
    title: Steps
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: steps
  values:
    title:
    date: 2016-09-01 00:00:00 -0700

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
